# Pipeline pre testi akcie z GitHub Marketplace

name: Test site for publicly known js vulnerabilities
uses: lirantal/is-website-vulnerable@v1.14.11


on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: "https://laba.cz"
